[package]
name = "cce-color-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { git = "https://github.com/lsgalante/cce-ui.git", rev = "7c620ae1be2bd6b5d17c837d6e1d2f0be7343540" }
wayland-client = { version = "0.31", features = ["system"] }
calloop = "0.13.0"
tokio = { version = "1", features = ["full"] }

