[package]
name = "cce-color-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { git = "https://github.com/lsgalante/cce-ui.git", rev = "25989d64afc740daae92a0ee0852a79f2eb5621d" }
wayland-client = { version = "0.31", features = ["system"] }
calloop = "0.13.0"
tokio = { version = "1", features = ["full"] }

