[package]
name = "cce-color-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { git = "https://github.com/lsgalante/cce-ui.git", rev = "61e2cefd67d38c6414ff8c9c5ffff68e995995e8" }
wayland-client = { version = "0.31", features = ["system"] }
calloop = "0.13.0"
tokio = { version = "1", features = ["full"] }

